const topicsData = [
  'arts', 
  'automobiles', 
  'books', 
  'business', 
  'fashion', 
  'food', 
  'health', 
  'home', 
  'insider', 
  'magazine', 
  'movies', 
  'nyregion', 
  'obituaries', 
  'opinion', 
  'politics', 
  'realestate', 
  'science', 
  'sports', 
  'sundayreview', 
  'technology', 
  'theater', 
  't-magazine',  
  'upshot', 
  'us', 
];

export default topicsData;